
INSERT [dbo].[tblCeilingInterpretation] ([CeilingIntCode], [CeilingIntDesc], [AltLanguage], [SortOrder]) VALUES (N'H', N'Hospital', N'Hôpital', NULL)
INSERT [dbo].[tblCeilingInterpretation] ([CeilingIntCode], [CeilingIntDesc], [AltLanguage], [SortOrder]) VALUES (N'I', N'In-Patient', N'Soins ambulatoires', NULL)
INSERT [dbo].[tblConfirmationTypes] ([ConfirmationTypeCode], [ConfirmationType], [SortOrder], [AltLanguage]) VALUES (N'A', N'Local council', NULL, N'Conseil local')
INSERT [dbo].[tblConfirmationTypes] ([ConfirmationTypeCode], [ConfirmationType], [SortOrder], [AltLanguage]) VALUES (N'B', N'Municipality', NULL, N'Municipalité')
INSERT [dbo].[tblConfirmationTypes] ([ConfirmationTypeCode], [ConfirmationType], [SortOrder], [AltLanguage]) VALUES (N'C', N'State', NULL, N'Etat')
INSERT [dbo].[tblConfirmationTypes] ([ConfirmationTypeCode], [ConfirmationType], [SortOrder], [AltLanguage]) VALUES (N'D', N'Other', NULL, N'Autre')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Age', N'M', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'AntenatalAmountLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'ApprovalOfSMS', N'N', N'Family')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'BeneficiaryCard', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Ceiling1', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Ceiling2', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'CHFID', N'M', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'ClaimAdministrator', N'M', N'FindClaim, Claim, ClaimReview, ClaimFeedback')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Confirmation', N'O', N'Family, Insuree, OverviewFamily, ChangeFamily')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'ConfirmationNo', N'O', N'Family, Insuree, FindFamily, OverviewFamily, ChangeFamily')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'ConsultationAmountLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'ContributionCategory', N'O', N'Premium, FindPremium')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'CurrentAddress', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'CurrentDistrict', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'CurrentMunicipality', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'CurrentVillage', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Ded1', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Ded2', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'DeliveryAmountLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'DistrictOfFSP', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'DOB', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Education', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'ExpiryDate', N'M', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'FamilyType', N'O', N'Family, ChangeFamily')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'FirstServicePoint', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'FSP', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'FSPCategory', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'FSPDistrict', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Gender', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'GuaranteeNo', N'O', N'Claim, ClaimReview')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'HFLevel', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'HospitalizationAmountLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'IdentificationNumber', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'IdentificationType', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'InsureeEmail', N'O', N'Family, Insuree, FindFamily')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'LastName', N'M', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'lblItemCode', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'lblItemCodeL', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'lblItemLeftL', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'lblItemMinDate', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'lblServiceLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'lblServiceMinDate', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'MaritalStatus', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'OtherNames', N'M', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'PermanentAddress', N'O', N'Family, Insuree, ChangeFamily')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'PolicyStatus', N'M', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Poverty', N'O', N'Family, Insuree, Policy, Premium, FindFamily, ChangeFamily')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'ProductCode', N'M', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Profession', N'O', N'Family, Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'RegionOfFSP', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'Relationship', N'O', N'Insuree')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'SurgeryAmountLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'TotalAdmissionsLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'TotalAmount', N'N', N'AppPolicies')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'TotalAntenatalLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'TotalConsultationsLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'TotalDelivieriesLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'TotalSurgeriesLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblControls] ([FieldName], [Adjustibility], [Usage]) VALUES (N'TotalVisitsLeft', N'O', N'Search Insurance Number/Enquiry')
INSERT [dbo].[tblEducations] ([EducationId], [Education], [SortOrder], [AltLanguage]) VALUES (1, N'Nursery', NULL, N'Garderie')
INSERT [dbo].[tblEducations] ([EducationId], [Education], [SortOrder], [AltLanguage]) VALUES (2, N'Primary school', NULL, N'École primaire')
INSERT [dbo].[tblEducations] ([EducationId], [Education], [SortOrder], [AltLanguage]) VALUES (3, N'Secondary school', NULL, N'École secondaire')
INSERT [dbo].[tblEducations] ([EducationId], [Education], [SortOrder], [AltLanguage]) VALUES (4, N'University', NULL, N'Université')
INSERT [dbo].[tblEducations] ([EducationId], [Education], [SortOrder], [AltLanguage]) VALUES (5, N'Postgraduate studies', NULL, N'Études supérieures')
INSERT [dbo].[tblEducations] ([EducationId], [Education], [SortOrder], [AltLanguage]) VALUES (6, N'PHD', NULL, N'Doctorat')
INSERT [dbo].[tblEducations] ([EducationId], [Education], [SortOrder], [AltLanguage]) VALUES (7, N'Other', NULL, N'Autre')
INSERT [dbo].[tblFamilyTypes] ([FamilyTypeCode], [FamilyType], [SortOrder], [AltLanguage]) VALUES (N'C', N'Council', NULL, N'Conseil')
INSERT [dbo].[tblFamilyTypes] ([FamilyTypeCode], [FamilyType], [SortOrder], [AltLanguage]) VALUES (N'G', N'Organization', NULL, N'Organisation')
INSERT [dbo].[tblFamilyTypes] ([FamilyTypeCode], [FamilyType], [SortOrder], [AltLanguage]) VALUES (N'H', N'Household', NULL, N'Ménage')
INSERT [dbo].[tblFamilyTypes] ([FamilyTypeCode], [FamilyType], [SortOrder], [AltLanguage]) VALUES (N'O', N'Other', NULL, N'Autre')
INSERT [dbo].[tblFamilyTypes] ([FamilyTypeCode], [FamilyType], [SortOrder], [AltLanguage]) VALUES (N'P', N'Priests', NULL, N'Prètres')
INSERT [dbo].[tblFamilyTypes] ([FamilyTypeCode], [FamilyType], [SortOrder], [AltLanguage]) VALUES (N'S', N'Students', NULL, N'Etudiants')
INSERT [dbo].[tblFamilyTypes] ([FamilyTypeCode], [FamilyType], [SortOrder], [AltLanguage]) VALUES (N'T', N'Teachers', NULL, N'Enseignant')
INSERT [dbo].[tblGender] ([Code], [Gender], [AltLanguage], [SortOrder]) VALUES (N'F', N'Female', N'Femme', 2)
INSERT [dbo].[tblGender] ([Code], [Gender], [AltLanguage], [SortOrder]) VALUES (N'M', N'Male', N'Homme', 1)
INSERT [dbo].[tblGender] ([Code], [Gender], [AltLanguage], [SortOrder]) VALUES (N'O', N'Other', N'Autre', 3)
INSERT [dbo].[tblHFSublevel] ([HFSublevel], [HFSublevelDesc], [SortOrder], [AltLanguage]) VALUES (N'I', N'Integrated', NULL, N'Intégré ')
INSERT [dbo].[tblHFSublevel] ([HFSublevel], [HFSublevelDesc], [SortOrder], [AltLanguage]) VALUES (N'N', N'No Sublevel', NULL, N'Aucun sous-niveau')
INSERT [dbo].[tblHFSublevel] ([HFSublevel], [HFSublevelDesc], [SortOrder], [AltLanguage]) VALUES (N'R', N'Reference', NULL, N'Référence')
INSERT [dbo].[tblIdentificationTypes] ([IdentificationCode], [IdentificationTypes], [AltLanguage], [SortOrder]) VALUES (N'D', N'Driver''s License', N'Permis de conduire', NULL)
INSERT [dbo].[tblIdentificationTypes] ([IdentificationCode], [IdentificationTypes], [AltLanguage], [SortOrder]) VALUES (N'N', N'National ID', N'Carte d''identité', NULL)
INSERT [dbo].[tblIdentificationTypes] ([IdentificationCode], [IdentificationTypes], [AltLanguage], [SortOrder]) VALUES (N'P', N'Passport', N'Passeport', NULL)
INSERT [dbo].[tblIdentificationTypes] ([IdentificationCode], [IdentificationTypes], [AltLanguage], [SortOrder]) VALUES (N'V', N'Voter Card', N'Carte d''électeur', NULL)
SET IDENTITY_INSERT [dbo].[tblIMISDefaults] ON 

INSERT [dbo].[tblIMISDefaults] ([DefaultID], [PolicyRenewalInterval], [FTPHost], [FTPUser], [FTPPassword], [FTPPort], [FTPEnrollmentFolder], [AssociatedPhotoFolder], [FTPClaimFolder], [FTPFeedbackFolder], [FTPPolicyRenewalFolder], [FTPPhoneExtractFolder], [FTPOffLineExtractFolder], [AppVersionBackEnd], [AppVersionEnquire], [AppVersionEnroll], [AppVersionRenewal], [AppVersionFeedback], [AppVersionClaim], [OffLineHF], [WinRarFolder], [DatabaseBackupFolder], [OfflineCHF], [SMSLink], [SMSIP], [SMSUserName], [SMSPassword], [SMSSource], [SMSDlr], [SMSType], [AppVersionFeedbackRenewal], [AppVersionImis]) VALUES (1, 14, N'', N'', N'', 0, N'/Images/Submitted', N'/Images/Updated', N'', N'', N'', N'', N'', CAST(1.2 AS Decimal(3, 1)), CAST(0.0 AS Decimal(3, 1)), CAST(0.0 AS Decimal(3, 1)), CAST(0.0 AS Decimal(3, 1)), CAST(0.0 AS Decimal(3, 1)), CAST(0.0 AS Decimal(3, 1)), 0, N'C:\Program Files (x86)\WinRAR\', N'', 0, N'', N'', N'', N'', N'', 1, 1, CAST(1.2 AS Decimal(3, 1)), CAST(0.0 AS Decimal(3, 1)))
SET IDENTITY_INSERT [dbo].[tblIMISDefaults] OFF
INSERT [dbo].[tblIMISDefaultsPhone] ([RuleName], [RuleValue], [Usage]) VALUES (N'AllowInsureeWithoutPhoto', 0, 'Allow synchronization of Insurees without a Photo.')
INSERT [dbo].[tblIMISDefaultsPhone] ([RuleName], [RuleValue], [Usage]) VALUES (N'AllowFamilyWithoutPolicy', 0, 'Allow synchronization of Families without a Policy.')
INSERT [dbo].[tblIMISDefaultsPhone] ([RuleName], [RuleValue], [Usage]) VALUES (N'AllowPolicyWithoutPremium', 0, 'Allow synchronization of Policies without a Contribution. If ShowPaymentOption is false, this rule value is read as true.')
INSERT [dbo].[tblIMISDefaultsPhone] ([RuleName], [RuleValue], [Usage]) VALUES (N'ShowPaymentOption', 1, 'Show or hide the Payment option to allow or not to add a Contribution for a Policy. ')
INSERT [dbo].[tblLanguages] ([LanguageCode], [LanguageName], [SortOrder]) VALUES (N'en', N'English', 1) -- By default english is set as primary language, required by SMS
INSERT [dbo].[tblLanguages] ([LanguageCode], [LanguageName], [SortOrder]) VALUES (N'fr', N'Français', 2)
INSERT [dbo].[tblLegalForms] ([LegalFormCode], [LegalForms], [SortOrder], [AltLanguage]) VALUES (N'C', N'Charity', NULL, N'Charité')
INSERT [dbo].[tblLegalForms] ([LegalFormCode], [LegalForms], [SortOrder], [AltLanguage]) VALUES (N'D', N'District organization', NULL, N'Organisation du district')
INSERT [dbo].[tblLegalForms] ([LegalFormCode], [LegalForms], [SortOrder], [AltLanguage]) VALUES (N'G', N'Government', NULL, N'Gouvernement')
INSERT [dbo].[tblLegalForms] ([LegalFormCode], [LegalForms], [SortOrder], [AltLanguage]) VALUES (N'P', N'Private organization', NULL, N'Organisation privée')
SET IDENTITY_INSERT [dbo].[tblLocations] ON 

INSERT [dbo].[tblLocations] ([LocationId], [LocationUUID], [LocationCode], [LocationName], [ParentLocationId], [LocationType], [ValidityFrom], [ValidityTo], [LegacyId], [AuditUserId], [MalePopulation], [FemalePopulation], [OtherPopulation], [Families]) VALUES (1, newid(), N'R0001', N'Region', NULL, N'R', CURRENT_TIMESTAMP, NULL, NULL, -1, NULL, NULL, NULL, NULL)
INSERT [dbo].[tblLocations] ([LocationId], [LocationUUID], [LocationCode], [LocationName], [ParentLocationId], [LocationType], [ValidityFrom], [ValidityTo], [LegacyId], [AuditUserId], [MalePopulation], [FemalePopulation], [OtherPopulation], [Families]) VALUES (2, newid(), N'D0001', N'Dummy', 1, N'D', CURRENT_TIMESTAMP, NULL, NULL, -1, NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[tblLocations] OFF
INSERT [dbo].[tblPayerType] ([Code], [PayerType], [AltLanguage], [SortOrder]) VALUES (N'C', N'Co-operative', N'Coopérative', NULL)
INSERT [dbo].[tblPayerType] ([Code], [PayerType], [AltLanguage], [SortOrder]) VALUES (N'D', N'Donor', N'Donateur', NULL)
INSERT [dbo].[tblPayerType] ([Code], [PayerType], [AltLanguage], [SortOrder]) VALUES (N'G', N'Government', N'Gouvernement', NULL)
INSERT [dbo].[tblPayerType] ([Code], [PayerType], [AltLanguage], [SortOrder]) VALUES (N'L', N'Local Authority', N'Autorité locale', NULL)
INSERT [dbo].[tblPayerType] ([Code], [PayerType], [AltLanguage], [SortOrder]) VALUES (N'O', N'Other', N'Autre', NULL)
INSERT [dbo].[tblPayerType] ([Code], [PayerType], [AltLanguage], [SortOrder]) VALUES (N'P', N'Private Organization', N'Organisation privée', NULL)
INSERT [dbo].[tblProfessions] ([ProfessionId], [Profession], [SortOrder], [AltLanguage]) VALUES (1, N'Housewife', NULL, N'Femme au foyer')
INSERT [dbo].[tblProfessions] ([ProfessionId], [Profession], [SortOrder], [AltLanguage]) VALUES (2, N'Employee', NULL, N'Employé')
INSERT [dbo].[tblProfessions] ([ProfessionId], [Profession], [SortOrder], [AltLanguage]) VALUES (3, N'Self Employee', NULL, N'Indépendant')
INSERT [dbo].[tblProfessions] ([ProfessionId], [Profession], [SortOrder], [AltLanguage]) VALUES (4, N'Others', NULL, N'Autres')
INSERT [dbo].[tblRelations] ([RelationId], [Relation], [SortOrder], [AltLanguage]) VALUES (1, N'Brother/Sister', NULL, N'Frère/soeur')
INSERT [dbo].[tblRelations] ([RelationId], [Relation], [SortOrder], [AltLanguage]) VALUES (2, N'Father/Mother', NULL, N'Père/Mère')
INSERT [dbo].[tblRelations] ([RelationId], [Relation], [SortOrder], [AltLanguage]) VALUES (3, N'Uncle/Aunt', NULL, N'Oncle/tante')
INSERT [dbo].[tblRelations] ([RelationId], [Relation], [SortOrder], [AltLanguage]) VALUES (4, N'Son/Daughter', NULL, N'Fils/fille')
INSERT [dbo].[tblRelations] ([RelationId], [Relation], [SortOrder], [AltLanguage]) VALUES (5, N'Grand parents', NULL, N'Grands/parents')
INSERT [dbo].[tblRelations] ([RelationId], [Relation], [SortOrder], [AltLanguage]) VALUES (6, N'Employee', NULL, N'Employé')
INSERT [dbo].[tblRelations] ([RelationId], [Relation], [SortOrder], [AltLanguage]) VALUES (7, N'Others', NULL, N'Autres')
INSERT [dbo].[tblRelations] ([RelationId], [Relation], [SortOrder], [AltLanguage]) VALUES (8, N'Spouse', NULL, N'Époux')
SET IDENTITY_INSERT [dbo].[tblRole] ON 

INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (1, newid(), N'Enrolment Officer', N'Agents d''affiliation', 1, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (2, newid(), N'Manager', N'Manager', 2, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (3, newid(), N'Accountant', N'Comptable', 4, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (4, newid(), N'Clerk', N'Employé de bureau', 8, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (5, newid(), N'Medical Officer', N'Médecin', 16, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (6, newid(), N'Scheme Administrator', N'Administrateur du régime d''assurance', 32, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (7, newid(), N'IMIS Administrator', N'Gestionnaire IMIS', 64, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (8, newid(), N'Receptionist', N'Réceptionniste', 128, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (9, newid(), N'Claim Administrator', N'Gestionnaire de remboursement', 256, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (10, newid(), N'Claim Contributor', N'Contributeur de remboursement', 512, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (11, newid(), N'HF Administrator', N'Gestionnaire d''établissement de santé', 524288, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRole] ([RoleID], [RoleUUID], [RoleName], [AltLanguage], [IsSystem], [IsBlocked], [ValidityFrom], [ValidityTo], [AuditUserID], [LegacyID]) VALUES (12, newid(), N'Offline Administrator', N'Administrateur Offline', 1048576, 0, CURRENT_TIMESTAMP, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[tblRole] OFF
SET IDENTITY_INSERT [dbo].[tblRoleRight] ON 

INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (1, 1, 101001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (2, 1, 101002, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (3, 1, 101003, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (4, 1, 101004, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (5, 1, 101101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (6, 1, 101102, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (7, 1, 101103, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (8, 1, 101104, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (9, 1, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (10, 1, 101201, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (11, 1, 101202, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (12, 1, 101203, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (13, 1, 101204, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (14, 1, 101205, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (15, 1, 101301, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (16, 1, 101302, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (17, 1, 101303, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (18, 1, 101304, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (19, 1, 111001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (20, 1, 111009, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (21, 6, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (22, 6, 121001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (23, 6, 121002, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (24, 6, 121003, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (25, 6, 121004, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (26, 6, 121005, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (27, 6, 121101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (28, 6, 121102, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (29, 6, 121103, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (30, 6, 121104, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (31, 6, 121201, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (32, 6, 121202, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (33, 6, 121203, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (34, 6, 121204, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (35, 6, 121205, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (36, 6, 121301, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (37, 6, 121302, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (38, 6, 121303, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (39, 6, 121304, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (40, 6, 121305, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (41, 6, 121401, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (42, 6, 121402, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (43, 6, 121403, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (44, 6, 121404, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (45, 6, 122101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (46, 6, 122102, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (47, 6, 122103, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (48, 6, 122104, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (49, 6, 121501, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (50, 6, 121502, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (51, 6, 121503, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (52, 6, 121504, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (53, 6, 121601, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (54, 6, 121602, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (55, 6, 121603, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (56, 6, 121604, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (57, 6, 121801, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (58, 6, 121802, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (59, 6, 121803, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (60, 6, 121804, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (61, 6, 131001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (62, 6, 131002, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (63, 6, 131003, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (64, 6, 131004, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (65, 6, 131101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (66, 6, 131102, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (67, 6, 131103, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (68, 6, 131104, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (69, 6, 131105, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (70, 6, 131106, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (71, 6, 131209, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (72, 7, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (73, 7, 121701, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (74, 7, 121702, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (75, 7, 121703, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (76, 7, 121704, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (77, 7, 121901, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (78, 7, 121902, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (79, 7, 121903, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (80, 7, 121904, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (81, 7, 121905, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (82, 7, 131005, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (83, 7, 131006, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (84, 7, 131207, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (85, 7, 131301, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (86, 7, 131302, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (87, 7, 131303, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (88, 7, 131304, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (89, 7, 122000, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (90, 7, 122001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (91, 7, 122002, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (92, 7, 122003, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (93, 7, 122004, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (94, 7, 122005, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (95, 3, 101001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (96, 3, 101101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (97, 3, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (98, 3, 101201, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (99, 3, 101301, CURRENT_TIMESTAMP, NULL, NULL, NULL)
GO
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (100, 3, 101401, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (101, 3, 101402, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (102, 3, 101403, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (103, 3, 101404, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (104, 3, 111101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (105, 3, 111102, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (106, 3, 111103, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (107, 3, 131204, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (108, 3, 131205, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (109, 3, 131206, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (110, 3, 131210, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (111, 3, 131211, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (112, 3, 131212, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (113, 3, 131213, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (114, 3, 131214, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (115, 3, 131215, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (116, 3, 131216, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (117, 3, 131217, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (118, 3, 131218, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (119, 3, 131219, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (120, 3, 131220, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (121, 3, 131221, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (122, 3, 131222, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (123, 3, 131401, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (124, 9, 111001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (125, 9, 111002, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (126, 9, 111004, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (127, 9, 111005, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (128, 9, 111006, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (129, 9, 111007, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (130, 4, 101001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (131, 4, 101002, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (132, 4, 101003, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (133, 4, 101004, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (134, 4, 101101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (135, 4, 101102, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (136, 4, 101103, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (137, 4, 101104, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (138, 4, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (139, 4, 101201, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (140, 4, 101202, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (141, 4, 101203, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (142, 4, 101204, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (143, 4, 101205, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (144, 4, 101301, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (145, 4, 101302, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (146, 4, 101303, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (147, 4, 101304, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (148, 2, 131201, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (149, 2, 131202, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (150, 2, 131203, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (151, 2, 131208, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (152, 2, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (153, 5, 111001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (154, 5, 111008, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (155, 5, 111009, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (156, 5, 111010, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (157, 5, 111011, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (158, 5, 131223, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (159, 8, 101001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (160, 8, 101101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (161, 8, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (162, 8, 101201, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (163, 10, 111001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (164, 10, 111002, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (165, 10, 111005, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (166, 12, 121701, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (167, 12, 121702, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (168, 12, 121703, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (169, 12, 121704, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (170, 12, 131101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (171, 12, 131103, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (172, 12, 131301, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (173, 12, 131302, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (174, 12, 131303, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (175, 12, 131304, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (176, 11, 121701, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (177, 11, 121702, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (178, 11, 121703, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (179, 11, 121704, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (180, 11, 131101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (181, 11, 131103, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (182, 11, 131301, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (183, 11, 131302, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (184, 11, 131303, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (185, 11, 131304, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (186, 9, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (187, 1, 131200, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (188, 1, 131201, CURRENT_TIMESTAMP, NULL, NULL, NULL)
--OTC-49:The system role Claim Administrator role doesn't have the required rights
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (189, 9, 101001, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (190, 9, 101101, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (191, 9, 101201, CURRENT_TIMESTAMP, NULL, NULL, NULL)
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (192, 9, 111012, CURRENT_TIMESTAMP, NULL, NULL, NULL)
--OTC-66:The Scheme Administrator role needs the Renewal Upload right
INSERT [dbo].[tblRoleRight] ([RoleRightID], [RoleID], [RightID], [ValidityFrom], [ValidityTo], [AuditUserId], [LegacyID]) VALUES (193, 6, 131107, CURRENT_TIMESTAMP, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[tblRoleRight] OFF
SET IDENTITY_INSERT [dbo].[tblUserRole] ON 

INSERT [dbo].[tblUserRole] ([UserRoleID], [UserID], [RoleID], [ValidityFrom], [ValidityTo], [AudituserID], [LegacyID]) VALUES (1, 1, 1, CURRENT_TIMESTAMP, NULL, 1, NULL)
INSERT [dbo].[tblUserRole] ([UserRoleID], [UserID], [RoleID], [ValidityFrom], [ValidityTo], [AudituserID], [LegacyID]) VALUES (2, 1, 2, CURRENT_TIMESTAMP, NULL, 1, NULL)
INSERT [dbo].[tblUserRole] ([UserRoleID], [UserID], [RoleID], [ValidityFrom], [ValidityTo], [AudituserID], [LegacyID]) VALUES (3, 1, 3, CURRENT_TIMESTAMP, NULL, 1, NULL)
INSERT [dbo].[tblUserRole] ([UserRoleID], [UserID], [RoleID], [ValidityFrom], [ValidityTo], [AudituserID], [LegacyID]) VALUES (4, 1, 4, CURRENT_TIMESTAMP, NULL, 1, NULL)
INSERT [dbo].[tblUserRole] ([UserRoleID], [UserID], [RoleID], [ValidityFrom], [ValidityTo], [AudituserID], [LegacyID]) VALUES (5, 1, 5, CURRENT_TIMESTAMP, NULL, 1, NULL)
INSERT [dbo].[tblUserRole] ([UserRoleID], [UserID], [RoleID], [ValidityFrom], [ValidityTo], [AudituserID], [LegacyID]) VALUES (6, 1, 6, CURRENT_TIMESTAMP, NULL, 1, NULL)
INSERT [dbo].[tblUserRole] ([UserRoleID], [UserID], [RoleID], [ValidityFrom], [ValidityTo], [AudituserID], [LegacyID]) VALUES (7, 1, 7, CURRENT_TIMESTAMP, NULL, 1, NULL)
INSERT [dbo].[tblUserRole] ([UserRoleID], [UserID], [RoleID], [ValidityFrom], [ValidityTo], [AudituserID], [LegacyID]) VALUES (8, 1, 8, CURRENT_TIMESTAMP, NULL, 1, NULL)
INSERT [dbo].[tblUserRole] ([UserRoleID], [UserID], [RoleID], [ValidityFrom], [ValidityTo], [AudituserID], [LegacyID]) VALUES (9, 1, 9, CURRENT_TIMESTAMP, NULL, 1, NULL)
INSERT [dbo].[tblUserRole] ([UserRoleID], [UserID], [RoleID], [ValidityFrom], [ValidityTo], [AudituserID], [LegacyID]) VALUES (10, 1, 10, CURRENT_TIMESTAMP, NULL, 1, NULL)
SET IDENTITY_INSERT [dbo].[tblUserRole] OFF
SET IDENTITY_INSERT [dbo].[tblUsers] ON 

INSERT [dbo].[tblUsers] ([UserID], [UserUUID], [LanguageID], [LastName], [OtherNames], [Phone], [LoginName], [RoleID], [HFID], [ValidityFrom], [ValidityTo], [LegacyID], [AuditUserID], [password], [DummyPwd], [EmailId], [PrivateKey], [StoredPassword], [PasswordValidity], [IsAssociated]) VALUES (1, newid(), N'en', N'Admin', N'Admin', N'', N'Admin', 1023, 0, CURRENT_TIMESTAMP, NULL, NULL, 0, 0x001699E55A06FA79F4CA0D06EF15096C0200000008EC898F797930F85853F08FCA1DC839CF5B4754C00C625E8C56F51E4334231B, NULL, NULL, N'C1C224B03CD9BC7B6A86D77F5DACE40191766C485CD55DC48CAF9AC873335D6F', N'2776C32451229C92B2F8995C38E4386CC4F6CC9888EE77A26F326A0083363002', NULL, NULL)
SET IDENTITY_INSERT [dbo].[tblUsers] OFF
SET IDENTITY_INSERT [dbo].[tblUsersDistricts] ON 

INSERT [dbo].[tblUsersDistricts] ([UserDistrictID], [UserID], [LocationId], [ValidityFrom], [ValidityTo], [LegacyID], [AuditUserID]) VALUES (1, 1, 2, CURRENT_TIMESTAMP, NULL, NULL, -1)
SET IDENTITY_INSERT [dbo].[tblUsersDistricts] OFF
